api_login_check:
    path: /api/login_check

api:
    resource: '.'
    type:     'api_platform'
    prefix: '/api'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
    prefix: '/api'
